version: '3'
services: 
    db:
        image: postgres:11
        env_file: 
            - .env
        volumes: 
            - "postgres_data:/var/lib/postgresql/data/"

    web:
        build: .
        command: python manage.py runserver 0.0.0.0:5000
        volumes: 
            - .:/code
        env_file: 
            - .env
        ports: 
            - "5000:5000"
        depends_on: 
            - db
volumes: 
    postgres_data: