# Generated by Django 3.1.4 on 2021-01-05 11:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Footwear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('quantity_in_stock', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47')], max_length=3)),
                ('category', models.CharField(choices=[('Shoes', 'Shoes'), ('Slippers', 'Slippers'), ('Sandals', 'Sandals'), ('Others', 'Others')], max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shoe_batch', to='inventory.batch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('quantity_in_stock', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('T-Shirt', 'T-Shirt'), ('Shirt', 'Shirt'), ('Polo', 'Polo')], max_length=20)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clothes_batch', to='inventory.batch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('quantity_in_stock', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Sunglasses', 'Sunglasses'), ('Bags', 'Bags'), ('Watch', 'Watch'), ('Belt', 'Belt'), ('Wallet', 'Wallet')], max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='accessory_batch', to='inventory.batch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
