# Generated by Django 3.1.4 on 2021-01-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name_plural': 'Accessories'},
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name_plural': 'Clothes'},
        ),
        migrations.AlterModelOptions(
            name='footwear',
            options={'verbose_name_plural': 'Footwears'},
        ),
        migrations.AddField(
            model_name='accessory',
            name='product_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clothes',
            name='product_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='footwear',
            name='product_number',
            field=models.IntegerField(default=0),
        ),
    ]
